### PR TITLE
Added aditional Features

### PR DESCRIPTION
**Pull request by MarcelRoozekrans**
- Added IDiagnostics interface
- Added FileVersioninfo
- Added Process

### CODE REVIEW

**Comment by schlotter** [comment]
This looks useful! Any chance of getting it merged to `master`?

**Comment by schlotter** [comment]
I'm using `System.Diagnostics.Abstractions` with this PR and it works fine for me. Anything missing from the PR that I can help adding?

I would really like to see getting it merged.

**Comment by MarcelRoozekrans** [comment]
@schlotter We need to have @davidwhitney  to merge it :)

**Comment by davidwhitney** [comment]
I'll get on this later today 🖤

**Comment by davidwhitney** [comment]
I'll get on this later today 🖤

**Comment by schlotter** [comment]
@davidwhitney Would it be possible to merge this PR? If you need support, please let me know.

**Comment by davidwhitney** [comment]
Holy hell, I'm so sorry :) First thing in the morning, post-it on my monitor to get this merged in :)

**Pull request merged**
